title: Anusha Chimmili
logo: /assets/img/image.png
description: >
  Accomplished Data Scientist and Advocate for <strong>Diversity in Tech</strong>
show_downloads: true
theme: jekyll-theme-minimal
resume: /assets/resume/resume.pdf
