title: Anusha Chimmili
logo: /assets/img/image1.png
description: >
  <h3><strong>Accomplished Data Scientist and an Advocate for Diversity in Tech</strong><br></h3><a href="https://www.linkedin.com/in/your-linkedin-profile" target="_blank">View My LinkedIn Profile</a>
# show_downloads: true
theme: jekyll-theme-minimal
resume: /assets/resume/resume.pdf
