title: Anusha Chimmili
logo: /assets/img/image1.png
description: >
  <h3><strong>Accomplished Data Scientist and Advocate for Diversity in Tech</strong></h3>
# show_downloads: true
theme: jekyll-theme-minimal
resume: /assets/resume/resume.pdf
